### ISSUE TITLE
百度云界面内没有出现pd下载的图标

### ISSUE THREAD

**Issue by 0xC000005** [monkeyWie/baiduyun-helper#12]
如题

**Comment by 0xC000005** [comment]
现在直接就是尝试启动网盘客户端了，怕不是百度改了api

**Comment by LewChich** [comment]
如图也不显示。
![qq 20181020163317](https://user-images.githubusercontent.com/12713435/47253477-e5721d00-d485-11e8-8c55-e77a6ceb457c.png)

**Comment by azure990** [comment]
![px](https://user-images.githubusercontent.com/39117167/47254154-9a113c00-d490-11e8-91b7-586fa5420f0c.jpg)
只显示PX-百度云盘-fix插件的下载按钮，不显示PD下载按钮

**Comment by 0xC000005** [comment]
![image](https://user-images.githubusercontent.com/29427196/47260822-4a724680-d477-11e8-8b42-72fd922e8cff.png)
没有注入还行

**Comment by acscript** [comment]
我也是多次刷新网盘页面不出现PD下载的按钮。后来尝试清除历史后显示按钮，但是直链下载提示创建任务失败，错误代码400。不知道如何解决

**Comment by monkeyWie** [comment]
开启全局代理

**Comment by BAWWH** [comment]
请问为什么3.1.2版本的Proxyee看不见百度云的插件啊

**Comment by Kingmanganese** [comment]
对了，我的版本是3.2 我是用proxyee-down-main.jar这个包运行的，看了一下程序目录，该有的都有。我这个是把2.5 版本和3.2版本放一起了，所以有些乱。
![image](https://user-images.githubusercontent.com/33016473/47421025-4a917f80-d7b2-11e8-8b34-6aa93ae2278f.png)

**Comment by monkeyWie** [comment]
扩展没生效的话可以用插件接管代理试试：https://github.com/proxyee-down-org/proxyee-down/wiki/%E4%BD%BF%E7%94%A8SwitchyOmega%E6%8E%A5%E7%AE%A1%E4%BB%A3%E7%90%86

**Comment by Light--** [comment]
> 扩展没生效的话可以用插件接管代理试试：https://github.com/proxyee-down-org/proxyee-down/wiki/%E4%BD%BF%E7%94%A8SwitchyOmega%E6%8E%A5%E7%AE%A1%E4%BB%A3%E7%90%86

还是不行，没有pd下载按钮
