### ISSUE TITLE
用百度网盘直链下载时，创建任务失败，400错误是怎么回事

### ISSUE THREAD

**Issue by jy869455072** [monkeyWie/baiduyun-helper#14]
用百度网盘直链下载时，创建任务失败，400错误是怎么回事

**Comment by acscript** [comment]
+1.
我也是多次刷新网盘页面不出现PD下载的按钮。后来尝试清除历史后显示按钮，但是直链下载提示创建任务失败，错误代码400。不知道如何解决
即使使用推送下载也是失败的，求助啊。这么棒的工具不要挂

**Comment by justiony** [comment]
> 什么版本啊

![image](https://user-images.githubusercontent.com/38231754/47336535-cb714e00-d6c2-11e8-8f0f-deafcddc1414.png)
