### ISSUE TITLE
可否小文件不分片下载？

### ISSUE THREAD

**Issue by nkbai** [monkeyWie/baiduyun-helper#2]
对于几十k，没有超过1M的文件，没必要分成32片下载，这样反而下载不下来。

**Comment by monkeyWie** [comment]
创建任务的时候可以手动设置连接数啊

**Comment by nkbai** [comment]
但是发送批量任务的时候呢？我一个文件夹下面有不少小文件，有几个是大文件。
小文件实在没必要设置很多连接数，只有大文件才有意义。

**Comment by monkeyWie** [comment]
3.2版本小文件会自适应连接数的

**Comment by nkbai** [comment]
已经切换到3.2了， 但是没注意小文件下载问题，多谢，我试试

**Comment by monkeyWie** [comment]
这个大小还不会进行调整连接数，几B的那种才会
