### ISSUE TITLE
百度云的扩展更新成0.32还是没有解决问题

### ISSUE THREAD

**Issue by endingly** [monkeyWie/baiduyun-helper#26]
**系统：Windows10**
**软件版本：0.32**
**扩展版本：0.32**  

仍然是卡在0%，过了一会之后就会显示失败  
需要指出的是，**压缩链接下载**是可以使用的

**Comment by hihila** [comment]
same problem; 显示失败

**Comment by monkeyWie** [comment]
已更新到0.34,社区链接：https://community.pdown.org/topic/128
