### ISSUE TITLE
今天更新了proxy down,打开百度下载页面，显示不了pd按钮了

### ISSUE THREAD

**Issue by zookfish** [monkeyWie/baiduyun-helper#3]

**Comment by mynameisshiy** [comment]
我也是遇到了，必须开全局代理才会显示PD按钮，而且是显示两个。
![image](https://user-images.githubusercontent.com/8981574/47067180-07b43280-d21b-11e8-99da-81dea6e68243.png)

**Comment by monkeyWie** [comment]
@mynameisshiy 删掉一个，重复安装了

**Comment by Carol-Li** [comment]
刷新页面之后就没了PD按钮emmm

**Comment by cuiYuhe** [comment]
很好的软件。但是我遇到一个问题：前两天刚使用本软件，可以下载。今天再打开firefox 不显示了，google也不显示。重新安装插件也不管用，打开了全局代理。救助
