### ISSUE TITLE
更新0.33新版下载没速度

### ISSUE THREAD

**Issue by 87zrjojo** [monkeyWie/baiduyun-helper#37]
等了半天就是没速度，没速度，没速度。。。。

**Comment by 18006059800** [comment]
换回 0.31 或 0.30 就正常了
到安装路径目录中的 main/extensions ，下载并解压附件压缩包进行替换就可以了
[baiduYun.zip](https://github.com/monkeyWie/baiduyun-helper/files/2570823/baiduYun.zip)

**Comment by monkeyWie** [comment]
参考：https://community.pdown.org/topic/128
