### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by StempyXP** [monkeyWie/baiduyun-helper#75]
下载后未报错，但文件并没有被添加至任务列表，刷新也没用

**Comment by Illyasviels** [comment]
+1

**Comment by zmxbaiye** [comment]
我的也是，怎么解决？

**Comment by Eisx11o** [comment]
不能用了，点击下载，闪一下就没了。

**Comment by SanShikiDan** [comment]
我的也是，求解决

**Comment by cxwithyxy** [comment]
[baiduyun-helper_2.zip](https://github.com/monkeyWie/baiduyun-helper/files/3266960/baiduyun-helper_2.zip)
找回旧的提交, 再build, 感觉还能用一下

**Comment by mrdulin** [comment]
+1

**Comment by monkeyWie** [comment]
已经修复，参考#80
