### ISSUE TITLE
扩展中心无任何扩展

### ISSUE THREAD

**Issue by leon-ytl** [monkeyWie/baiduyun-helper#79]

**Comment by monkeyWie** [comment]
服务器被墙了- -，可以先本地安装

**Comment by aofeng2009** [comment]
求本地安装方法

**Comment by monkeyWie** [comment]
下载这个，https://github.com/proxyee-down-org/proxyee-down-extension/archive/master.zip，然后解压出来每个目录都是一个扩展，本地安装选择对应目录就行

**Comment by aofeng2009** [comment]
点击红色下载按钮之后proxyee down 起不来是什么问题呢？

**Comment by sidney9111** [comment]
前2天空白，今天可以了，不过很多扩展都不能用

**Comment by monkeyWie** [comment]
服务器已恢复，百度云扩展也更新了
