### ISSUE TITLE
点击直链下载和批量下载都不行，只有压缩下载可用

### ISSUE THREAD

**Issue by tongjun741** [monkeyWie/baiduyun-helper#80]
Chrome报错：

`Access to XMLHttpRequest at 'https://d.pcs.baidu.com/rest/2.0/pcs/file?app_id=250528&channel=00000000000000000000000000000000&check_blue=1&clienttype=8&devuid=0&dtype=1&ehps=0&err_ver=1&es=1&esl=1&method=locatedownload&path=%2F%E8%BD%AF%E4%BB%B6%2F%E5%B8%9D%E5%9B%BD%E6%97%B6%E4%BB%A32.dmg&time=1561103991217&ver=4&version=6.0.0.12&vip=2' from origin 'https://pan.baidu.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by zwxs** [comment]
同，请大佬解决一下

**Comment by lengrongfu** [comment]
都不可用了，求解决

**Comment by freshirt** [comment]
一样，只有压缩可用

**Comment by tzhangZJU** [comment]
一样，只有压缩可用

**Comment by kuiZhang98** [comment]
现在全部都不能用了. 获取不到下载链接了

**Comment by ryulamp** [comment]
不能用了，直接下载只是闪一下，没有捕获链接。。。。。

**Comment by nvhanzijiuba** [comment]
一样的，点击压缩下载的时候，提示文件大于300M或者文件名中含+号

**Comment by 1234205a** [comment]
同求。。

**Comment by GammyKing** [comment]
同求，获取不到连接，无法拉起程序

**Comment by monkeyWie** [comment]
已经修复此BUG，升级扩展到0.36
![image](https://user-images.githubusercontent.com/13160176/61115857-fe17dc80-a4c5-11e9-96b4-2c715324f6f9.png)

**Comment by lqp0505** [comment]
0.36版的仍然有问题，直链下载和批量下载都不行，只有压缩下载可以用

**Comment by monkeyWie** [comment]
@lqp0505 你是在自己网盘下载的还是分享的链接里下载的呢？

**Comment by lqp0505** [comment]
你好，从别人分享的链接中下载。

您的意思是，先存到自己的网盘，然后从自己的网盘下载，就可以了？

发件人: monkeyWie <notifications@github.com>
发送时间: 2019年7月15日 9:20
收件人: monkeyWie/baiduyun-helper <baiduyun-helper@noreply.github.com>
抄送: lqp0505 <lqp0505@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [monkeyWie/baiduyun-helper] 点击直链下载和批量下载都不行，只有压缩下载可用 (#80)


@lqp0505<https://github.com/lqp0505> 你是在自己网盘下载的还是分享的链接里下载的呢？

**Comment by monkeyWie** [comment]
@lqp0505 是的，分享的暂时下载不了
