### ISSUE TITLE
点击批量推送下载，任务显示推送成功，但是在proxyee里面并没有显示任务

### ISSUE THREAD

**Issue by Pan006** [monkeyWie/baiduyun-helper#82]
![image](https://user-images.githubusercontent.com/37503389/62353660-b83abb00-b53d-11e9-9c3d-8af4606eea8a.png)
![image](https://user-images.githubusercontent.com/37503389/62353672-bffa5f80-b53d-11e9-9bb1-9adb5c28b20b.png)

**Comment by ldwnt** [comment]
相同问题
软件版本：3.4
百度云扩展版本：0.36
请求：
https://d.pcs.baidu.com/rest/2.0/pcs/file?...
{"error_code":31326,"error_msg":"user is not authorized, hitcode:119","request_id":xxx}

**Comment by TiffanyChou21** [comment]
相同问题
有的时候重启proxyeedown可以解决有的时候怎么都不行

**Comment by yxsllgz** [comment]
遇到同样问题了，现在可以解决了吗

**Comment by 134546** [comment]
我也是

**Comment by ronghuitar** [comment]
相同问题

**Comment by Polobay** [comment]
相同问题 推送成功但是不显示任务 什么时候可以解决呢？

**Comment by hanzexu66** [comment]
相同问题

**Comment by EpicPeter** [comment]
相同问题

**Comment by Unclemole** [comment]
相同问题

**Comment by cswangchen** [comment]
same problem

**Comment by monkeyWie** [comment]
分享的链接已经不行了，要保存到自己网盘里下载

**Comment by monkeyWie** [comment]
参考：https://github.com/monkeyWie/baiduyun-helper/releases/tag/0.37
