### ISSUE TITLE
这插件现在还能用吗

### ISSUE THREAD

**Issue by zoukun120** [monkeyWie/baiduyun-helper#90]
我看proxyee-down项目已经停止了，是不是之前下载到本地的也不能用了呢？比如3.4版本。
我离线下载了baiduyun-helper，放到Proxyee Down\main\extensions下，去百度云网页并没有”pd下载“按钮，是不是本插件也不能使用了呢？

**Comment by monkeyWie** [comment]
没有显示的话应该就是不能用了吧，毕竟这个插件也很久没维护过了，可能百度的脚本更新了已经。
